name: aicuzaro
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  simple_gradient_text: ^1.3.0
  flutter_svg: ^2.0.10+1
  google_fonts: 6.1.0
  animate_do: ^3.3.4
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_database: ^10.4.0
  dash_chat_2: ^0.0.18
  chat_gpt_sdk: ^2.2.5
  image_picker: ^1.0.8
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  image_picker_web: ^3.1.1
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.4
  flutter_dotenv: ^5.1.0
  like_button: ^2.0.5
  webview_flutter: ^2.0.4
  webview_flutter_web: ^0.1.0+1
  youtube_player_flutter: ^9.0.1
 
  

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/design.png
    - lib/assets/master-web-hero-image.png
    - lib/assets/start.jpeg
    - lib/assets/start.png
    - lib/assets/res2.png
    - lib/assets/arrow.png
    - lib/assets/arrow2.png
    - lib/assets/robotics.png
    - lib/assets/footer.png
    - lib/assets/startup.png
    - lib/assets/1.JPG
    - lib/assets/2.JPG
    - lib/assets/3.png
    - lib/assets/4.jpeg
    - lib/assets/5.jpg
    - lib/assets/6.jpeg
    - lib/assets/7.png
    - lib/assets/8.png
    - lib/assets/9.png
    - lib/assets/10.png
    - lib/assets/11.png
    - lib/assets/social.png
    - lib/assets/appr.png

